### ISSUE TITLE
feat: 支持同步删除

### ISSUE THREAD

**Issue by RWDai** [xjxjin/alist-sync#1]

**Comment by xjxjin** [comment]
可否详细描述一下

**Comment by RWDai** [comment]
就是现在是可以支持两个目录相互同步新增，但是如果要两个目录某个目录删除了文件另外一个目录怎么样可以同步删除，现在的话应该是被删除的会重新同步。

**Comment by RWDai** [comment]
同步删除的逻辑我认为应该是这样的
获取源路径所有文件夹中modified最晚的时间A，然后扫描目的路径所有不在源路径并且modified时间早于A的文件就是需要删除的文件。

**Comment by xjxjin** [comment]
> 同步删除的逻辑我认为应该是这样的 获取源路径所有文件夹中modified最晚的时间A，然后扫描目的路径所有不在源路径并且修改时间早于A的文件就是需要删除的文件。

你这个开销比较大，后续我可以考虑再开个脚本，定期清理多余文件，因为还存在一个文件存在不同的源目录的情况，如果有合适的方案，也可以提供一下

**Comment by RWDai** [comment]
impl by #8
