### ISSUE TITLE
同步报错

### ISSUE THREAD

**Issue by chaomarks** [xjxjin/alist-sync#3]
获取不到源目录，用的最新版的xhofe/alist:v3.35.0-ffmpeg
![image](https://github.com/xjxjin/alist-sync/assets/93130581/ad5cb6d7-91d7-4795-8234-200bc2e0b04f)

**Comment by xjxjin** [comment]
我这边使用同版本，暂未复现，有时候可能会因为网络原因，导致各种问题，可以多试几次
