### ISSUE TITLE
获取目录内容失败

### ISSUE THREAD

**Issue by gaodyoffice** [xjxjin/alist-sync#4]
![image](https://github.com/xjxjin/alist-sync/assets/100499224/1ed1f57a-78b7-4dbd-9251-e644834513d7)
获取目录内容失败，无法复制。

**Comment by xjxjin** [comment]
你的alist是什么版本

**Comment by gaodyoffice** [comment]
> 你的alist是什么版本
v3.35.0
电脑win10系统

**Comment by xjxjin** [comment]
我在本地暂时未复现，可否多执行几次，有时候可能因为网络原因导致各种意外问题，你那边执行是每次都是这个问题么，是从哪种云盘复制到哪种云盘

**Comment by zza774886285** [comment]
我的因为没有/dav这个文件，所以删了dav，能运行
